export enum CategoryDto {
  SOFTWARE_DEVELOPMENT = "Software Development",
  WEB_DEVELOPMENT = "Web Development",
  MOBILE_DEVELOPMENT = "Mobile Development",
  DATA_SCIENCE = "Data Science",
  MACHINE_LEARNING = "Machine Learning",
  CYBERSECURITY = "Cybersecurity",
  CLOUD_COMPUTING = "Cloud Computing",
  DEVOPS = "DevOps",
  UI_UX_DESIGN = "UI/UX Design",
  QUALITY_ASSURANCE = "Quality Assurance (QA)",
  PROJECT_MANAGEMENT = "IT Project Management",
  DATABASE_ADMINISTRATION = "Database Administration",
  NETWORK_ENGINEERING = "Network Engineering",
  IT_SUPPORT = "IT Support",
  BUSINESS_INTELLIGENCE = "Business Intelligence",
  GAME_DEVELOPMENT = "Game Development",
  EMBEDDED_SYSTEMS = "Embedded Systems",
  ROBOTICS = "Robotics",
}