import { ICompany } from "src/interfaces/ICompany";

export const CompaniesArray: ICompany[] = [
  {
    id: "1",
    image: "/google.png",
    name: "Google",
    description:
      "Google is a global technology company that specializes in internet-related services and products, including search, advertising, cloud computing, and software.",

    jobs: [
      {
        id: "1-7655",
        title: "HR Specialist",
        description: "Deliver top-notch customer service experiences.",
        company: "Google",
        location: "Paris",
        category: "Finance",
        salary: "$124075",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Freelance",
        vacancies: 5,
      },
      {
        id: "1-2040",
        title: "HR Specialist",
        description: "Support internal teams and improve workflows.",
        company: "Google",
        location: "Sydney",
        category: "Operations",
        salary: "$141681",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Temporary",
        vacancies: 10,
      },
      {
        id: "1-8903",
        title: "Sales Associate",
        description: "Design and implement new business strategies.",
        company: "Google",
        location: "Paris",
        category: "Finance",
        salary: "$51100",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Temporary",
        vacancies: 3,
      },
    ],
  },
  {
    id: "2",
    image: "/mcdonalds.png",
    name: "McDonalds",
    description: "McDonalds logo",
    jobs: [
      {
        id: "2-7819",
        title: "Marketing Manager",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "McDonalds",
        location: "Tokyo",
        category: "Customer Service",
        salary: "$110074",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 4,
      },
      {
        id: "2-7739",
        title: "Electrical Technician",
        description: "Design and implement new business strategies.",
        company: "McDonalds",
        location: "Buenos Aires",
        category: "Marketing",
        salary: "$40895",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Full-Time",
        vacancies: 3,
      },
      {
        id: "2-9784",
        title: "UX Designer",
        description: "Deliver top-notch customer service experiences.",
        company: "McDonalds",
        location: "London",
        category: "Engineering",
        salary: "$63265",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Freelance",
        vacancies: 3,
      },
    ],
  },
  {
    id: "3",
    image: "/amazon.png",
    name: "Amazon",
    description: "Amazon logo",
    jobs: [
      {
        id: "3-5941",
        title: "HR Specialist",
        description: "Deliver top-notch customer service experiences.",
        company: "Amazon",
        location: "New York",
        category: "Technology",
        salary: "$38187",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 9,
      },
      {
        id: "3-5854",
        title: "Marketing Manager",
        description: "Deliver top-notch customer service experiences.",
        company: "Amazon",
        location: "San Francisco",
        category: "Logistics",
        salary: "$71440",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 3,
      },
      {
        id: "3-8403",
        title: "Marketing Manager",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Amazon",
        location: "San Francisco",
        category: "Logistics",
        salary: "$145029",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "On-site",
        type: "Full-Time",
        vacancies: 1,
      },
    ],
  },
  {
    id: "4",
    image: "/visa.png",
    name: "Visa",
    description: "Visa logo",
    jobs: [
      {
        id: "4-8791",
        title: "Marketing Manager",
        description: "Design and implement new business strategies.",
        company: "Visa",
        location: "London",
        category: "Logistics",
        salary: "$99701",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Temporary",
        vacancies: 2,
      },
      {
        id: "4-9440",
        title: "Warehouse Operator",
        description: "Support internal teams and improve workflows.",
        company: "Visa",
        location: "London",
        category: "Customer Service",
        salary: "$42003",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Temporary",
        vacancies: 9,
      },
      {
        id: "4-5831",
        title: "Mechanical Engineer",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Visa",
        location: "S\u00e3o Paulo",
        category: "Logistics",
        salary: "$104408",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Freelance",
        vacancies: 9,
      },
    ],
  },
  {
    id: "5",
    image: "/apple.png",
    name: "Apple",
    description: "Apple logo",
    jobs: [
      {
        id: "5-6195",
        title: "Software Engineer",
        description: "Support internal teams and improve workflows.",
        company: "Apple",
        location: "Sydney",
        category: "Technology",
        salary: "$85086",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 1,
      },
      {
        id: "5-8245",
        title: "Finance Analyst",
        description: "Join our team to help build innovative solutions.",
        company: "Apple",
        location: "Berlin",
        category: "Marketing",
        salary: "$38020",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 1,
      },
      {
        id: "5-6627",
        title: "Graphic Designer",
        description: "Deliver top-notch customer service experiences.",
        company: "Apple",
        location: "Tokyo",
        category: "Customer Service",
        salary: "$143451",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Full-Time",
        vacancies: 7,
      },
    ],
  },
  {
    id: "6",
    image: "/samsung.webp",
    name: "Samsung",
    description: "Samsung logo",
    jobs: [
      {
        id: "6-7922",
        title: "Marketing Manager",
        description: "Join our team to help build innovative solutions.",
        company: "Samsung",
        location: "London",
        category: "Operations",
        salary: "$125257",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Part-Time",
        vacancies: 10,
      },
      {
        id: "6-9915",
        title: "Software Engineer",
        description: "Support internal teams and improve workflows.",
        company: "Samsung",
        location: "Tokyo",
        category: "Technology",
        salary: "$95414",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 6,
      },
      {
        id: "6-4682",
        title: "Barista",
        description: "Design and implement new business strategies.",
        company: "Samsung",
        location: "San Francisco",
        category: "Marketing",
        salary: "$116948",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Freelance",
        vacancies: 1,
      },
    ],
  },
  {
    id: "7",
    image: "/coca-cola.png",
    name: "Coca Cola",
    description: "Coca Cola logo",
    jobs: [
      {
        id: "7-8917",
        title: "Finance Analyst",
        description: "Deliver top-notch customer service experiences.",
        company: "Coca Cola",
        location: "Buenos Aires",
        category: "Logistics",
        salary: "$66962",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "On-site",
        type: "Temporary",
        vacancies: 3,
      },
      {
        id: "7-8671",
        title: "Product Manager",
        description: "Deliver top-notch customer service experiences.",
        company: "Coca Cola",
        location: "S\u00e3o Paulo",
        category: "Engineering",
        salary: "$114311",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Part-Time",
        vacancies: 3,
      },
      {
        id: "7-6075",
        title: "Project Manager",
        description: "Deliver top-notch customer service experiences.",
        company: "Coca Cola",
        location: "Sydney",
        category: "Finance",
        salary: "$34075",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 1,
      },
    ],
  },
  {
    id: "8",
    image: "/mercadolibre.png",
    name: "Mercado Libre",
    description: "Mercado Libre logo",
    jobs: [
      {
        id: "8-5430",
        title: "Sales Associate",
        description: "Join our team to help build innovative solutions.",
        company: "Mercado Libre",
        location: "Toronto",
        category: "Operations",
        salary: "$47126",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 7,
      },
      {
        id: "8-3406",
        title: "Delivery Driver",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Mercado Libre",
        location: "Toronto",
        category: "Marketing",
        salary: "$74449",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Temporary",
        vacancies: 2,
      },
      {
        id: "8-6557",
        title: "Account Executive",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Mercado Libre",
        location: "S\u00e3o Paulo",
        category: "Logistics",
        salary: "$76057",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Freelance",
        vacancies: 9,
      },
    ],
  },
  {
    id: "9",
    image: "/nike.png",
    name: "Nike",
    description: "Nike logo",
    jobs: [
      {
        id: "9-2132",
        title: "Cashier",
        description: "Design and implement new business strategies.",
        company: "Nike",
        location: "Paris",
        category: "Marketing",
        salary: "$108094",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Remote",
        type: "Temporary",
        vacancies: 9,
      },
      {
        id: "9-8209",
        title: "Warehouse Operator",
        description: "Join our team to help build innovative solutions.",
        company: "Nike",
        location: "S\u00e3o Paulo",
        category: "Customer Service",
        salary: "$46946",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Internship",
        vacancies: 10,
      },
      {
        id: "9-4674",
        title: "Barista",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Nike",
        location: "Buenos Aires",
        category: "Engineering",
        salary: "$57155",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 10,
      },
    ],
  },
  {
    id: "10",
    image: "/carrefour.png",
    name: "Carrefour",
    description: "Carrefour logo",
    jobs: [
      {
        id: "10-2267",
        title: "HR Specialist",
        description: "Design and implement new business strategies.",
        company: "Carrefour",
        location: "Paris",
        category: "Retail",
        salary: "$146804",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 6,
      },
      {
        id: "10-5845",
        title: "Finance Analyst",
        description: "Design and implement new business strategies.",
        company: "Carrefour",
        location: "Berlin",
        category: "Technology",
        salary: "$143446",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Remote",
        type: "Internship",
        vacancies: 2,
      },
      {
        id: "10-7709",
        title: "Finance Analyst",
        description: "Support internal teams and improve workflows.",
        company: "Carrefour",
        location: "Berlin",
        category: "Finance",
        salary: "$82047",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Internship",
        vacancies: 1,
      },
    ],
  },
  {
    id: "11",
    image: "/microsoft.png",
    name: "Microsoft",
    description: "Microsoft logo",
    jobs: [
      {
        id: "11-6447",
        title: "Finance Analyst",
        description: "Deliver top-notch customer service experiences.",
        company: "Microsoft",
        location: "Toronto",
        category: "Marketing",
        salary: "$99889",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "On-site",
        type: "Temporary",
        vacancies: 3,
      },
      {
        id: "11-7783",
        title: "Finance Analyst",
        description: "Join our team to help build innovative solutions.",
        company: "Microsoft",
        location: "S\u00e3o Paulo",
        category: "Marketing",
        salary: "$144075",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Freelance",
        vacancies: 6,
      },
      {
        id: "11-7500",
        title: "Finance Analyst",
        description: "Design and implement new business strategies.",
        company: "Microsoft",
        location: "S\u00e3o Paulo",
        category: "Logistics",
        salary: "$125899",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "On-site",
        type: "Internship",
        vacancies: 2,
      },
    ],
  },
  {
    id: "12",
    image: "/meta.png",
    name: "Meta",
    description: "Meta logo",
    jobs: [
      {
        id: "12-8513",
        title: "Marketing Manager",
        description: "Support internal teams and improve workflows.",
        company: "Meta",
        location: "Paris",
        category: "Customer Service",
        salary: "$119547",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Freelance",
        vacancies: 7,
      },
      {
        id: "12-6970",
        title: "Cashier",
        description: "Deliver top-notch customer service experiences.",
        company: "Meta",
        location: "New York",
        category: "Engineering",
        salary: "$131589",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 1,
      },
      {
        id: "12-3552",
        title: "Cashier",
        description: "Design and implement new business strategies.",
        company: "Meta",
        location: "Berlin",
        category: "Operations",
        salary: "$126943",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 1,
      },
    ],
  },
  {
    id: "13",
    image: "/x.webp",
    name: "X",
    description: "X logo",
    jobs: [
      {
        id: "13-9056",
        title: "Account Executive",
        description: "Design and implement new business strategies.",
        company: "X",
        location: "Sydney",
        category: "Finance",
        salary: "$139710",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Temporary",
        vacancies: 9,
      },
      {
        id: "13-6082",
        title: "Customer Service Representative",
        description: "Join our team to help build innovative solutions.",
        company: "X",
        location: "New York",
        category: "Retail",
        salary: "$78860",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Temporary",
        vacancies: 8,
      },
      {
        id: "13-2269",
        title: "Delivery Driver",
        description: "Support internal teams and improve workflows.",
        company: "X",
        location: "Toronto",
        category: "Technology",
        salary: "$49370",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Full-Time",
        vacancies: 4,
      },
    ],
  },
  {
    id: "14",
    image: "/adidas.png",
    name: "Adidas",
    description: "Adidas logo",
    jobs: [
      {
        id: "14-9570",
        title: "Sales Associate",
        description: "Deliver top-notch customer service experiences.",
        company: "Adidas",
        location: "S\u00e3o Paulo",
        category: "Logistics",
        salary: "$148836",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "On-site",
        type: "Temporary",
        vacancies: 3,
      },
      {
        id: "14-6504",
        title: "UX Designer",
        description: "Join our team to help build innovative solutions.",
        company: "Adidas",
        location: "Sydney",
        category: "Operations",
        salary: "$146932",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Part-Time",
        vacancies: 2,
      },
      {
        id: "14-4967",
        title: "Sales Associate",
        description: "Deliver top-notch customer service experiences.",
        company: "Adidas",
        location: "Berlin",
        category: "Finance",
        salary: "$73018",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 5,
      },
    ],
  },
  {
    id: "15",
    image: "/netflix.webp",
    name: "Netflix",
    description: "Netflix logo",
    jobs: [
      {
        id: "15-9219",
        title: "Project Manager",
        description: "Join our team to help build innovative solutions.",
        company: "Netflix",
        location: "Sydney",
        category: "Finance",
        salary: "$73550",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 5,
      },
      {
        id: "15-6820",
        title: "UX Designer",
        description: "Deliver top-notch customer service experiences.",
        company: "Netflix",
        location: "New York",
        category: "Retail",
        salary: "$127201",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 4,
      },
      {
        id: "15-7828",
        title: "Marketing Manager",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Netflix",
        location: "London",
        category: "Marketing",
        salary: "$32815",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Internship",
        vacancies: 3,
      },
    ],
  },
  {
    id: "16",
    image: "/paypal.webp",
    name: "PayPal",
    description: "PayPal logo",
    jobs: [
      {
        id: "16-2209",
        title: "Software Engineer",
        description: "Support internal teams and improve workflows.",
        company: "PayPal",
        location: "S\u00e3o Paulo",
        category: "Customer Service",
        salary: "$39845",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Internship",
        vacancies: 8,
      },
      {
        id: "16-4928",
        title: "Operations Coordinator",
        description: "Design and implement new business strategies.",
        company: "PayPal",
        location: "Buenos Aires",
        category: "Marketing",
        salary: "$136141",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Internship",
        vacancies: 4,
      },
      {
        id: "16-6167",
        title: "HR Specialist",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "PayPal",
        location: "San Francisco",
        category: "Customer Service",
        salary: "$70901",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 6,
      },
    ],
  },
  {
    id: "17",
    image: "/intel.png",
    name: "Intel",
    description: "Intel logo",
    jobs: [
      {
        id: "17-2705",
        title: "Mechanical Engineer",
        description: "Join our team to help build innovative solutions.",
        company: "Intel",
        location: "S\u00e3o Paulo",
        category: "Operations",
        salary: "$139370",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 3,
      },
      {
        id: "17-7218",
        title: "Software Engineer",
        description: "Design and implement new business strategies.",
        company: "Intel",
        location: "Buenos Aires",
        category: "Engineering",
        salary: "$87489",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Remote",
        type: "Internship",
        vacancies: 4,
      },
      {
        id: "17-5978",
        title: "Electrical Technician",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Intel",
        location: "Paris",
        category: "Marketing",
        salary: "$94189",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Freelance",
        vacancies: 1,
      },
    ],
  },
  {
    id: "18",
    image: "/uber.png",
    name: "Uber",
    description: "Uber logo",
    jobs: [
      {
        id: "18-2048",
        title: "Account Executive",
        description: "Join our team to help build innovative solutions.",
        company: "Uber",
        location: "Paris",
        category: "Marketing",
        salary: "$91758",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "On-site",
        type: "Internship",
        vacancies: 10,
      },
      {
        id: "18-8603",
        title: "Project Manager",
        description: "Deliver top-notch customer service experiences.",
        company: "Uber",
        location: "New York",
        category: "Marketing",
        salary: "$143073",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 1,
      },
      {
        id: "18-8343",
        title: "Cashier",
        description: "Support internal teams and improve workflows.",
        company: "Uber",
        location: "Sydney",
        category: "Customer Service",
        salary: "$142723",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 10,
      },
    ],
  },
  {
    id: "19",
    image: "/starbucks.png",
    name: "Starbucks",
    description: "Starbucks logo",
    jobs: [
      {
        id: "19-5604",
        title: "Warehouse Operator",
        description: "Design and implement new business strategies.",
        company: "Starbucks",
        location: "Tokyo",
        category: "Technology",
        salary: "$99019",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Remote",
        type: "Full-Time",
        vacancies: 8,
      },
      {
        id: "19-5210",
        title: "Graphic Designer",
        description: "Support internal teams and improve workflows.",
        company: "Starbucks",
        location: "San Francisco",
        category: "Customer Service",
        salary: "$59905",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "On-site",
        type: "Part-Time",
        vacancies: 1,
      },
      {
        id: "19-7138",
        title: "HR Specialist",
        description: "Deliver top-notch customer service experiences.",
        company: "Starbucks",
        location: "S\u00e3o Paulo",
        category: "Customer Service",
        salary: "$125309",
        createdAt: "2025-06-13",
        status: "Expired",
        modality: "Hybrid",
        type: "Freelance",
        vacancies: 5,
      },
    ],
  },
  {
    id: "20",
    image: "/spotify.png",
    name: "Spotify",
    description: "Spotify logo",
    jobs: [
      {
        id: "20-4177",
        title: "Product Manager",
        description: "Design and implement new business strategies.",
        company: "Spotify",
        location: "S\u00e3o Paulo",
        category: "Engineering",
        salary: "$84937",
        createdAt: "2025-06-13",
        status: "Urgent",
        modality: "Hybrid",
        type: "Temporary",
        vacancies: 6,
      },
      {
        id: "20-4089",
        title: "Finance Analyst",
        description: "Join our team to help build innovative solutions.",
        company: "Spotify",
        location: "Berlin",
        category: "Marketing",
        salary: "$68829",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Remote",
        type: "Full-Time",
        vacancies: 4,
      },
      {
        id: "20-1309",
        title: "Electrical Technician",
        description: "We need motivated individuals for day-to-day tasks.",
        company: "Spotify",
        location: "S\u00e3o Paulo",
        category: "Retail",
        salary: "$85213",
        createdAt: "2025-06-13",
        status: "Active",
        modality: "Hybrid",
        type: "Full-Time",
        vacancies: 9,
      },
    ],
  },
];
