import { IJob } from "../interfaces/IJOB";

export const JobsArray: IJob[] = [
  {
    id: "1",
    title: "Frontend Developer",
    description: "We are seeking a skilled React developer to build modern web applications.",
    company: "TechNova",
    location: "New York, USA",
    category: "IT & Software",
    salary: "$60,000 - $80,000",
    createdAt: "2025-06-01",
    status: "Active",
    modality: "Remote",
    type: "Full-Time",
  },
  {
    id: "2",
    title: "Marketing Assistant",
    description: "Assist in campaign creation and market research activities across digital channels.",
    company: "BrightMark",
    location: "Los Angeles, USA",
    category: "Marketing",
    salary: "$35,000 - $45,000",
    createdAt: "2025-05-20",
    status: "Expired",
    modality: "On-site",
    type: "Internship",
  },
  {
    id: "3",
    title: "Backend Engineer",
    description: "Join our engineering team to develop scalable APIs using Node.js.",
    company: "CloudCore",
    location: "Toronto, Canada",
    category: "IT & Software",
    salary: "$70,000 - $90,000",
    createdAt: "2025-06-03",
    status: "Urgent",
    modality: "Hybrid",
    type: "Full-Time",
  },
  {
    id: "4",
    title: "UI/UX Designer",
    description: "Design user-centric interfaces and collaborate closely with frontend developers.",
    company: "DesignWave",
    location: "London, UK",
    category: "Design",
    salary: "$50,000 - $65,000",
    createdAt: "2025-05-28",
    status: "Active",
    modality: "Remote",
    type: "Freelance",
  },
  {
    id: "5",
    title: "Customer Support Agent",
    description: "Provide excellent customer service and resolve client issues efficiently.",
    company: "HelpSphere",
    location: "Miami, USA",
    category: "Customer Service",
    createdAt: "2025-06-05",
    status: "Active",
    modality: "On-site",
    type: "Part-Time",
  },
];